### ISSUE TITLE
Missing image from Docker server makes server crash

### ISSUE THREAD

**Issue by akalipetis** [opendevelop/opendevelop#19]
If the requested image is missing from the assigned Docker server, the project crashes.
It should return a 404 error instead.

Additional improvement would be to download image to every Docker server when added from the Admin panel.

**Comment by parisk** [comment]
Regarding

> It should return a 404 error instead.

I had this debate with @marioskogias. I think that this should return a 401 error. 404 means that the given resource was not found. Since a web resource is identified by the URL ([citation](http://en.wikipedia.org/wiki/Web_resource)) and the image is a POST parameter, therefore it is not part of the URL, 404 is not the proper status code. In my opinion the most suitable is 400.

Other than that, this issue will be processed and solved.
